- name: "Sanity checks"
  fail:
    msg: "action must be on of [install|delete|restart]"
  when: action not in ('install','delete','restart')

- name: "Sanity checks"
  fail:
    msg: "You cannot use both consul_tls_generate and consul_tls_provided"
  when: consul_use_tls and consul_tls_generate and consul_tls_provided

- include_tasks: "{{ action }}.yml"
  tags:
    - install
    - tls
    - configure
    - restart
