- name: Restart Consul
  systemd:
    name: consul
    state: restarted
    enabled: yes
  when: inventory_hostname in groups['consul_servers']

- name: Restart Consul Client
  systemd:
    name: consul_client
    state: restarted
    enabled: yes
  when: inventory_hostname in groups['consul_clients']